### PR TITLE
Fix composer typo

### PR DESCRIPTION
**Pull request by it-can**
Fix typo

### CODE REVIEW

**Review by tomschlick — APPROVED** [review]

**Comment by tomschlick** [comment]
It looks like the tests are failing related to test bench.

**Comment by it-can** [comment]
@tomschlick okay fixed the tests and added php7.4 to travis.

**Comment by it-can** [comment]
@tomschlick can you merge this? And also #25 ?

**Comment by it-can** [comment]
@tomschlick can you also merge #25 ? and release a new tag?

**Pull request merged**
